import React, { useState } from 'react';
import { 
  Zap, ArrowRight, Shield, Sparkles, Star, ChevronDown, Check, 
  MessageSquare, Layout, Search, Mail, Lock, Globe, Users, 
  Settings, BookOpen, Clock, Heart, ArrowUpRight
} from 'lucide-react';
import { motion } from 'motion/react';

interface LandingPageProps {
  onStart: () => void;
  onNavigateToBlog: () => void;
}

export default function LandingPage({ onStart, onNavigateToBlog }: LandingPageProps) {
  const [activeFaq, setActiveFaq] = useState<number | null>(null);
  const [pricingCycle, setPricingCycle] = useState<'monthly' | 'yearly'>('monthly');
  const [newsletterEmail, setNewsletterEmail] = useState('');
  const [newsletterSubscribed, setNewsletterSubscribed] = useState(false);

  const toggleFaq = (index: number) => {
    setActiveFaq(activeFaq === index ? null : index);
  };

  const pricingPlans = [
    {
      name: 'Starter',
      price: pricingCycle === 'monthly' ? 19 : 15,
      words: '20,000 words / mo',
      features: [
        'Access to 40+ Core Templates',
        'AI Chat Assistant (Standard)',
        '1 Brand Voice Blueprint',
        'Standard Document Editor',
        'Email Support',
        '1 Active User Seat'
      ],
      popular: false,
      cta: 'Start Free Trial'
    },
    {
      name: 'Pro',
      price: pricingCycle === 'monthly' ? 49 : 39,
      words: '100,000 words / mo',
      features: [
        'Access to 100+ Professional Templates',
        'AI Chat Assistant (Pro + Search Grounding)',
        'Unlimited Brand Voices',
        'SEO Toolkit & Audit Reports',
        'Rich Document Editor with Export',
        'AI Image Prompt Generator',
        'Multilingual Translation',
        'Priority Support',
        '3 Team Collaborator Seats'
      ],
      popular: true,
      cta: 'Claim Pro Membership'
    },
    {
      name: 'Enterprise',
      price: pricingCycle === 'monthly' ? 149 : 119,
      words: 'Unlimited words',
      features: [
        'Custom Fine-Tuned Brand Models',
        'dedicated Private Workspace',
        'Dedicated API access keys',
        'Unlimited Team Members',
        'SLA Guaranteed Uptime',
        'Dedicated Success Account Manager',
        'Custom Template Integration'
      ],
      popular: false,
      cta: 'Contact Sales'
    }
  ];

  const testimonials = [
    {
      name: 'Marcus Sterling',
      role: 'Founder at GrowthHack',
      content: 'ContentForge AI completely eliminated our content bottlenecks. We went from drafting 2 blog posts a week to 15 fully-optimized articles in a fraction of the time. The Brand Voice engine is uncanny.',
      rating: 5,
      avatar: 'MS'
    },
    {
      name: 'Elena Rostova',
      role: 'VP of Marketing at ScaleDev',
      content: 'The cold emails generated by this SaaS have an average 28% response rate, compared to our previous 11%. It is paid for itself within the first 48 hours of our launching campaign.',
      rating: 5,
      avatar: 'ER'
    },
    {
      name: 'Devon Chen',
      role: 'Creative Director at LoomAgencies',
      content: 'The custom templates and SEO audits are enterprise-grade. It doesn’t just spit out generic copy; it crafts deeply analytical outlines that actually rank on Google. Highly recommended!',
      rating: 5,
      avatar: 'DC'
    }
  ];

  const faqs = [
    {
      q: 'Which AI models power ContentForge AI?',
      a: 'We leverage a robust, multi-provider network using free/open-source and Google AI Studio free tier models. Our system dynamically selects and routes requests to the most optimal model (like Gemini 3.5 Flash, Llama 3.1, or Qwen) with automatic instant fallbacks to guarantee uninterrupted uptime.'
    },
    {
      q: 'How does the Brand Voice feature work?',
      a: 'You define your target audience, industry, preferred keywords, and core vocabulary rules. When you generate content, our system automatically wraps your custom brand blueprint around the underlying AI instructions, ensuring the output matches your precise writing style and brand identity perfectly.'
    },
    {
      q: 'Can I export my generated documents?',
      a: 'Absolutely! Our rich document editor supports instant exports to PDF, DOCX (Microsoft Word), and standard Markdown files, as well as quick copying to clipboard.'
    },
    {
      q: 'Do you charge for API usage?',
      a: 'No. ContentForge AI runs completely on free-tier, highly optimized open API networks, which is why we pass massive savings onto you. You only pay for your plan allocation without needing your own API keys.'
    }
  ];

  const handleNewsletterSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (newsletterEmail) {
      setNewsletterSubscribed(true);
      setNewsletterEmail('');
    }
  };

  return (
    <div id="landing-container" className="min-h-screen bg-[#fafafb] text-slate-900 selection:bg-violet-200">
      
      {/* Navigation Header */}
      <nav id="landing-nav" className="sticky top-0 z-50 glass-panel border-b border-slate-100 px-6 py-4">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center space-x-3 cursor-pointer" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>
            <div className="w-10 h-10 bg-gradient-to-tr from-violet-600 to-indigo-600 rounded-xl flex items-center justify-center text-white shadow-md shadow-violet-200">
              <Sparkles className="w-5 h-5 animate-pulse" />
            </div>
            <span className="font-display font-bold text-xl tracking-tight bg-gradient-to-r from-violet-600 to-indigo-600 bg-clip-text text-transparent">
              ContentForge AI
            </span>
          </div>
          
          <div className="hidden md:flex items-center space-x-8 text-sm font-medium text-slate-600">
            <a href="#features" className="hover:text-violet-600 transition-colors">Features</a>
            <a href="#pricing" className="hover:text-violet-600 transition-colors">Pricing</a>
            <a href="#testimonials" className="hover:text-violet-600 transition-colors">Testimonials</a>
            <a href="#faq" className="hover:text-violet-600 transition-colors">FAQ</a>
            <button onClick={onNavigateToBlog} className="hover:text-violet-600 transition-colors cursor-pointer text-left font-medium">Resources</button>
          </div>

          <div className="flex items-center space-x-4">
            <button 
              id="login-landing-btn"
              onClick={onStart}
              className="text-sm font-semibold text-slate-700 hover:text-violet-600 px-4 py-2 rounded-lg transition-colors"
            >
              Log In
            </button>
            <button 
              id="start-landing-btn"
              onClick={onStart}
              className="bg-violet-600 hover:bg-violet-700 text-white text-sm font-semibold px-5 py-2.5 rounded-xl shadow-lg shadow-violet-100 hover:shadow-violet-200 hover:-translate-y-0.5 active:translate-y-0 transition-all flex items-center space-x-2 cursor-pointer"
            >
              <span>Get Started</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <header id="hero" className="relative pt-20 pb-24 overflow-hidden px-6">
        <div className="absolute inset-0 bg-radial-gradient from-violet-50/50 via-transparent to-transparent -z-10" />
        <div className="max-w-5xl mx-auto text-center">
          
          {/* Animated Badge */}
          <div className="inline-flex items-center space-x-2 bg-violet-50 border border-violet-100/80 px-4 py-1.5 rounded-full text-violet-700 text-xs font-semibold mb-8 shadow-sm">
            <Zap className="w-3.5 h-3.5 fill-violet-700 text-violet-700" />
            <span>Introducing ContentForge AI SaaS Platform</span>
          </div>

          {/* Heading */}
          <h1 className="font-display font-extrabold text-4xl sm:text-6xl tracking-tight text-slate-900 leading-tight mb-6">
            The Enterprise Copilot for <br className="hidden sm:inline" />
            <span className="bg-gradient-to-r from-violet-600 to-indigo-600 bg-clip-text text-transparent">
              High-Converting Brand Copy
            </span>
          </h1>

          {/* Subheading */}
          <p className="max-w-2xl mx-auto text-slate-500 text-base sm:text-lg mb-10 leading-relaxed">
            Generate blog articles, persuasive Facebook ads, high-response sales emails, and complete SEO tag architectures in seconds—powered by fine-tuned free/open AI models. Enforce your unique brand voice automatically.
          </p>

          {/* CTA Group */}
          <div className="flex flex-col sm:flex-row items-center justify-center space-y-4 sm:space-y-0 sm:space-x-4 mb-16">
            <button 
              onClick={onStart}
              className="w-full sm:w-auto bg-violet-600 hover:bg-violet-700 text-white font-semibold px-8 py-4 rounded-xl shadow-xl shadow-violet-200 hover:shadow-violet-300 hover:-translate-y-0.5 transition-all flex items-center justify-center space-x-3 cursor-pointer"
            >
              <span>Launch ContentForge AI Free</span>
              <ArrowRight className="w-5 h-5" />
            </button>
            <a 
              href="#features"
              className="w-full sm:w-auto text-slate-600 hover:text-violet-600 font-semibold px-8 py-4 rounded-xl hover:bg-slate-50 transition-all flex items-center justify-center space-x-2"
            >
              <span>Explore Features</span>
            </a>
          </div>

          {/* Interface Teaser / Mockup */}
          <div className="relative max-w-4xl mx-auto bg-white rounded-2xl border border-slate-100 shadow-2xl p-3 sm:p-4 bg-gradient-to-b from-white to-slate-50">
            <div className="absolute -top-3 -right-3 bg-violet-600 text-white px-3.5 py-1.5 rounded-full text-xs font-bold flex items-center space-x-1.5 shadow-lg shadow-violet-300 animate-bounce">
              <Sparkles className="w-3.5 h-3.5" />
              <span>Real-Time Copywriting</span>
            </div>
            
            {/* Top bar mockup */}
            <div className="flex items-center space-x-2 border-b border-slate-100 pb-3 mb-4 text-slate-400">
              <div className="w-3 h-3 rounded-full bg-red-400" />
              <div className="w-3 h-3 rounded-full bg-yellow-400" />
              <div className="w-3 h-3 rounded-full bg-green-400" />
              <div className="text-xs bg-slate-100/80 px-4 py-1 rounded-md ml-4 text-slate-500 font-mono flex items-center space-x-2 w-56 sm:w-72">
                <Lock className="w-3 h-3" />
                <span className="truncate">contentforge.ai/dashboard</span>
              </div>
            </div>

            {/* Inner Dashboard Preview Grid */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-left p-2">
              <div className="md:col-span-1 border-r border-slate-100 pr-2">
                <div className="font-display font-bold text-sm text-slate-800 mb-3 flex items-center space-x-1.5">
                  <Layout className="w-4 h-4 text-violet-500" />
                  <span>Choose Template</span>
                </div>
                <div className="space-y-2">
                  <div className="p-2.5 rounded-lg bg-violet-50 border border-violet-100 flex items-center justify-between text-xs font-semibold text-violet-700">
                    <span className="flex items-center space-x-2">
                      <BookOpen className="w-3.5 h-3.5" />
                      <span>Blog Post Writer</span>
                    </span>
                    <Check className="w-3.5 h-3.5" />
                  </div>
                  <div className="p-2.5 rounded-lg hover:bg-slate-50 border border-slate-100 flex items-center text-xs text-slate-600 transition-colors">
                    <span className="flex items-center space-x-2">
                      <Mail className="w-3.5 h-3.5 text-slate-400" />
                      <span>Cold Outreach Email</span>
                    </span>
                  </div>
                  <div className="p-2.5 rounded-lg hover:bg-slate-50 border border-slate-100 flex items-center text-xs text-slate-600 transition-colors">
                    <span className="flex items-center space-x-2">
                      <Search className="w-3.5 h-3.5 text-slate-400" />
                      <span>SEO Tag Auditor</span>
                    </span>
                  </div>
                </div>
              </div>

              <div className="md:col-span-2 space-y-4">
                <div className="bg-slate-50 rounded-xl p-4 border border-slate-100">
                  <span className="text-xs font-mono font-bold text-violet-600 block mb-2">OUTPUT PREVIEW:</span>
                  <h3 className="font-display font-bold text-base text-slate-900 mb-2">10 Growth Hacking Frameworks for Early Stage Startups</h3>
                  <p className="text-xs text-slate-500 leading-relaxed mb-3">
                    Launch-hacking isn’t about buying programmatic banner ads. It’s about building loop mechanisms that turn every active subscriber into a brand evangelist...
                  </p>
                  <div className="flex items-center justify-between text-[11px] text-slate-400 font-mono border-t border-slate-200/60 pt-2.5">
                    <span className="flex items-center space-x-1.5">
                      <Clock className="w-3 h-3 text-slate-400" />
                      <span>AI Model: Gemini 3.5 Flash</span>
                    </span>
                    <span className="bg-violet-100 text-violet-700 px-2 py-0.5 rounded font-bold">128 words generated</span>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
      </header>

      {/* Trust & Stats Grid */}
      <section className="bg-white py-12 border-y border-slate-100">
        <div className="max-w-7xl mx-auto px-6 grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
          <div>
            <span className="font-display font-extrabold text-3xl sm:text-4xl text-slate-900">10M+</span>
            <p className="text-xs sm:text-sm text-slate-400 font-semibold mt-1 uppercase tracking-wider">Words Generated</p>
          </div>
          <div>
            <span className="font-display font-extrabold text-3xl sm:text-4xl text-slate-900">45k+</span>
            <p className="text-xs sm:text-sm text-slate-400 font-semibold mt-1 uppercase tracking-wider">Campaigns Drafted</p>
          </div>
          <div>
            <span className="font-display font-extrabold text-3xl sm:text-4xl text-slate-900">100+</span>
            <p className="text-xs sm:text-sm text-slate-400 font-semibold mt-1 uppercase tracking-wider">Pro Templates</p>
          </div>
          <div>
            <span className="font-display font-extrabold text-3xl sm:text-4xl text-slate-900">99.9%</span>
            <p className="text-xs sm:text-sm text-slate-400 font-semibold mt-1 uppercase tracking-wider">API Fallback Uptime</p>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section id="features" className="py-24 px-6 max-w-7xl mx-auto">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <span className="text-violet-600 text-sm font-extrabold uppercase tracking-widest block mb-3">Enterprise Modules</span>
          <h2 className="font-display font-bold text-3xl sm:text-4xl text-slate-900 tracking-tight">
            Everything you need to automate corporate copywriting
          </h2>
          <p className="text-slate-500 mt-4 leading-relaxed text-sm sm:text-base">
            Why jump between ChatGPT, Grammarly, and SEO checkers? ContentForge combines copywriting, collaboration, document editing, and optimization in a single premium hub.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          
          {/* Card 1 */}
          <div className="bg-white p-8 rounded-2xl border border-slate-100 shadow-sm hover:shadow-md hover:-translate-y-1 transition-all duration-300">
            <div className="w-12 h-12 bg-violet-100 text-violet-600 rounded-xl flex items-center justify-center mb-6">
              <Zap className="w-6 h-6" />
            </div>
            <h3 className="font-display font-bold text-lg text-slate-900 mb-3">100+ Professional Templates</h3>
            <p className="text-slate-500 text-sm leading-relaxed">
              Highly specialized forms for landing pages, Google ads, startup pitches, Amazon bullet points, and email sequences. Just enter basic values and get outputs instantly.
            </p>
          </div>

          {/* Card 2 */}
          <div className="bg-white p-8 rounded-2xl border border-slate-100 shadow-sm hover:shadow-md hover:-translate-y-1 transition-all duration-300">
            <div className="w-12 h-12 bg-violet-100 text-violet-600 rounded-xl flex items-center justify-center mb-6">
              <MessageSquare className="w-6 h-6" />
            </div>
            <h3 className="font-display font-bold text-lg text-slate-900 mb-3">Brand Voice Blueprinting</h3>
            <p className="text-slate-500 text-sm leading-relaxed">
              Define your guidelines, audience profile, vocabulary rules, and avoid list. Every generated post strictly follows your company voice.
            </p>
          </div>

          {/* Card 3 */}
          <div className="bg-white p-8 rounded-2xl border border-slate-100 shadow-sm hover:shadow-md hover:-translate-y-1 transition-all duration-300">
            <div className="w-12 h-12 bg-violet-100 text-violet-600 rounded-xl flex items-center justify-center mb-6">
              <Layout className="w-6 h-6" />
            </div>
            <h3 className="font-display font-bold text-lg text-slate-900 mb-3">Rich Document Editor</h3>
            <p className="text-slate-500 text-sm leading-relaxed">
              Draft, edit, and expand your articles directly inside a clean, modern canvas. Track history, add comments, and export to PDF or DOCX seamlessly.
            </p>
          </div>

          {/* Card 4 */}
          <div className="bg-white p-8 rounded-2xl border border-slate-100 shadow-sm hover:shadow-md hover:-translate-y-1 transition-all duration-300">
            <div className="w-12 h-12 bg-violet-100 text-violet-600 rounded-xl flex items-center justify-center mb-6">
              <Search className="w-6 h-6" />
            </div>
            <h3 className="font-display font-bold text-lg text-slate-900 mb-3">SEO Auditing Toolkit</h3>
            <p className="text-slate-500 text-sm leading-relaxed">
              Get meta titles, descriptions, optimized H1/H2 structures, SEO content scores, keyword density analyses, and schema code blocks.
            </p>
          </div>

          {/* Card 5 */}
          <div className="bg-white p-8 rounded-2xl border border-slate-100 shadow-sm hover:shadow-md hover:-translate-y-1 transition-all duration-300">
            <div className="w-12 h-12 bg-violet-100 text-violet-600 rounded-xl flex items-center justify-center mb-6">
              <Users className="w-6 h-6" />
            </div>
            <h3 className="font-display font-bold text-lg text-slate-900 mb-3">Team Collaboration Hub</h3>
            <p className="text-slate-500 text-sm leading-relaxed">
              Invite colleagues, toggle between Editor/Viewer roles, write feedback comments, and keep all content projects inside a shared safe dashboard.
            </p>
          </div>

          {/* Card 6 */}
          <div className="bg-white p-8 rounded-2xl border border-slate-100 shadow-sm hover:shadow-md hover:-translate-y-1 transition-all duration-300">
            <div className="w-12 h-12 bg-violet-100 text-violet-600 rounded-xl flex items-center justify-center mb-6">
              <Globe className="w-6 h-6" />
            </div>
            <h3 className="font-display font-bold text-lg text-slate-900 mb-3">Instant Translation Engine</h3>
            <p className="text-slate-500 text-sm leading-relaxed">
              Translate your blogs and newsletters to English, Tamil, Hindi, French, Spanish, German, Arabic, or Japanese with a single click.
            </p>
          </div>

        </div>
      </section>

      {/* Pricing Section */}
      <section id="pricing" className="py-24 bg-slate-50 border-y border-slate-100 px-6">
        <div className="max-w-7xl mx-auto">
          
          <div className="text-center max-w-3xl mx-auto mb-12">
            <span className="text-violet-600 text-sm font-extrabold uppercase tracking-widest block mb-3">Pricing Plans</span>
            <h2 className="font-display font-bold text-3xl sm:text-4xl text-slate-900 tracking-tight">
              Honest, predictable pricing for teams of all sizes
            </h2>
            <p className="text-slate-500 mt-4 leading-relaxed text-sm">
              All plans include free-tier routing, unified API keys, and collaborative storage. Choose the plan that fits your volume needs.
            </p>

            {/* Billing cycle toggler */}
            <div className="inline-flex items-center space-x-1.5 bg-slate-200/60 p-1 rounded-xl mt-8">
              <button 
                onClick={() => setPricingCycle('monthly')}
                className={`text-xs font-bold px-4 py-2 rounded-lg transition-all ${pricingCycle === 'monthly' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-800'}`}
              >
                Monthly billing
              </button>
              <button 
                onClick={() => setPricingCycle('yearly')}
                className={`text-xs font-bold px-4 py-2 rounded-lg transition-all ${pricingCycle === 'yearly' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-800'}`}
              >
                Yearly billing <span className="text-violet-600 text-[10px] font-extrabold uppercase bg-violet-100 px-1.5 py-0.5 rounded ml-1">Save 20%</span>
              </button>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-stretch max-w-5xl mx-auto">
            {pricingPlans.map((plan, i) => (
              <div 
                key={i} 
                className={`bg-white rounded-2xl border p-8 flex flex-col relative ${
                  plan.popular 
                    ? 'border-violet-600 ring-2 ring-violet-600/15 shadow-xl md:scale-105 z-10' 
                    : 'border-slate-200 shadow-sm hover:shadow-md'
                }`}
              >
                {plan.popular && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-violet-600 text-white text-xs font-bold px-4 py-1 rounded-full uppercase tracking-wider">
                    Most Popular
                  </div>
                )}
                
                <div>
                  <h3 className="font-display font-bold text-lg text-slate-900 mb-1">{plan.name}</h3>
                  <p className="text-xs text-slate-400 font-semibold uppercase tracking-wide mb-6">{plan.words}</p>
                  
                  <div className="flex items-baseline mb-6">
                    <span className="font-display font-extrabold text-4xl text-slate-900">${plan.price}</span>
                    <span className="text-sm text-slate-400 ml-1.5">/ mo</span>
                  </div>

                  <hr className="border-slate-100 mb-6" />

                  <ul className="space-y-3.5 mb-8 text-slate-600 text-xs sm:text-sm">
                    {plan.features.map((feat, fIdx) => (
                      <li key={fIdx} className="flex items-start space-x-3">
                        <Check className="w-4 h-4 text-violet-600 mt-0.5 flex-shrink-0" />
                        <span>{feat}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <button 
                  onClick={onStart}
                  className={`mt-auto w-full py-3 rounded-xl font-bold text-sm tracking-wide transition-all cursor-pointer ${
                    plan.popular
                      ? 'bg-violet-600 hover:bg-violet-700 text-white shadow-lg shadow-violet-200'
                      : 'bg-slate-100 hover:bg-slate-200 text-slate-800'
                  }`}
                >
                  {plan.cta}
                </button>
              </div>
            ))}
          </div>

        </div>
      </section>

      {/* Testimonials */}
      <section id="testimonials" className="py-24 max-w-7xl mx-auto px-6">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <span className="text-violet-600 text-sm font-extrabold uppercase tracking-widest block mb-3">Success Stories</span>
          <h2 className="font-display font-bold text-3xl sm:text-4xl text-slate-900 tracking-tight">
            Trusted by creators and modern agencies worldwide
          </h2>
          <p className="text-slate-500 mt-4 leading-relaxed text-sm sm:text-base">
            Read how professional digital marketers and high-velocity writing agencies leverage our SaaS to multiply their publishing capacity.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {testimonials.map((test, i) => (
            <div key={i} className="bg-white p-8 rounded-2xl border border-slate-100 shadow-sm flex flex-col justify-between">
              <div>
                <div className="flex items-center space-x-1 mb-6 text-yellow-400">
                  {[...Array(test.rating)].map((_, idx) => (
                    <Star key={idx} className="w-4 h-4 fill-yellow-400" />
                  ))}
                </div>
                <p className="text-slate-600 text-xs sm:text-sm leading-relaxed italic">
                  "{test.content}"
                </p>
              </div>
              
              <div className="flex items-center space-x-4 border-t border-slate-100 pt-6 mt-6">
                <div className="w-10 h-10 bg-violet-100 text-violet-700 font-bold font-display rounded-full flex items-center justify-center text-sm">
                  {test.avatar}
                </div>
                <div>
                  <h4 className="font-bold text-sm text-slate-900">{test.name}</h4>
                  <p className="text-[11px] text-slate-400 font-semibold uppercase">{test.role}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* FAQ Section */}
      <section id="faq" className="py-24 bg-slate-50 border-t border-slate-100 px-6">
        <div className="max-w-4xl mx-auto">
          
          <div className="text-center mb-16">
            <span className="text-violet-600 text-sm font-extrabold uppercase tracking-widest block mb-3">Got Questions?</span>
            <h2 className="font-display font-bold text-3xl text-slate-900 tracking-tight">
              Frequently Asked Questions
            </h2>
          </div>

          <div className="space-y-4">
            {faqs.map((faq, idx) => (
              <div key={idx} className="bg-white rounded-xl border border-slate-200/60 overflow-hidden shadow-sm">
                <button 
                  onClick={() => toggleFaq(idx)}
                  className="w-full text-left p-5 flex items-center justify-between text-slate-800 hover:text-violet-600 font-bold text-sm sm:text-base transition-colors"
                >
                  <span>{faq.q}</span>
                  <ChevronDown className={`w-5 h-5 text-slate-400 transition-transform ${activeFaq === idx ? 'rotate-180 text-violet-600' : ''}`} />
                </button>
                {activeFaq === idx && (
                  <div className="px-5 pb-5 pt-1 text-xs sm:text-sm text-slate-500 leading-relaxed border-t border-slate-50">
                    {faq.a}
                  </div>
                )}
              </div>
            ))}
          </div>

        </div>
      </section>

      {/* Footer & CTA / Newsletter */}
      <footer className="bg-slate-900 text-slate-300 pt-20 pb-12 px-6">
        <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-4 gap-12 pb-16 border-b border-slate-800">
          
          <div className="md:col-span-1 space-y-4">
            <div className="flex items-center space-x-3">
              <div className="w-9 h-9 bg-violet-600 rounded-lg flex items-center justify-center text-white font-bold text-lg">
                <Sparkles className="w-5 h-5" />
              </div>
              <span className="font-display font-extrabold text-lg text-white tracking-tight">
                ContentForge AI
              </span>
            </div>
            <p className="text-slate-400 text-xs sm:text-sm leading-relaxed">
              Premium content, ad, and email blueprints built dynamically using state-of-the-art open models.
            </p>
          </div>

          <div className="md:col-span-1 space-y-4">
            <h4 className="text-white text-xs font-extrabold uppercase tracking-widest">Resources</h4>
            <ul className="space-y-2 text-xs sm:text-sm text-slate-400">
              <li><button onClick={onNavigateToBlog} className="hover:text-white transition-colors cursor-pointer">SaaS Guides & Blogs</button></li>
              <li><a href="#features" className="hover:text-white transition-colors">Our Features</a></li>
              <li><a href="#pricing" className="hover:text-white transition-colors">Subscription Plans</a></li>
            </ul>
          </div>

          <div className="md:col-span-1 space-y-4">
            <h4 className="text-white text-xs font-extrabold uppercase tracking-widest">Company</h4>
            <ul className="space-y-2 text-xs sm:text-sm text-slate-400">
              <li><a href="#testimonials" className="hover:text-white transition-colors">Customer Reviews</a></li>
              <li><a href="#faq" className="hover:text-white transition-colors">Support FAQ</a></li>
              <li><span className="text-slate-500">Security Audit Logs</span></li>
            </ul>
          </div>

          <div className="md:col-span-1 space-y-4">
            <h4 className="text-white text-xs font-extrabold uppercase tracking-widest">Newsletter</h4>
            <p className="text-slate-400 text-xs sm:text-sm">Get copywriting hacks and AI workflow advice delivered weekly.</p>
            
            {newsletterSubscribed ? (
              <div className="bg-violet-900/40 border border-violet-800 px-4 py-2 rounded-lg text-xs font-semibold text-violet-300">
                ✓ Thank you for subscribing!
              </div>
            ) : (
              <form onSubmit={handleNewsletterSubmit} className="flex space-x-2">
                <input 
                  type="email" 
                  value={newsletterEmail}
                  onChange={(e) => setNewsletterEmail(e.target.value)}
                  placeholder="Enter your email" 
                  required
                  className="bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-xs text-white focus:outline-none focus:ring-1 focus:ring-violet-500 w-full"
                />
                <button type="submit" className="bg-violet-600 hover:bg-violet-700 text-white px-3.5 py-2 rounded-lg text-xs font-semibold transition-all cursor-pointer">
                  Join
                </button>
              </form>
            )}
          </div>

        </div>

        <div className="max-w-7xl mx-auto pt-8 flex flex-col sm:flex-row items-center justify-between text-xs text-slate-500 space-y-4 sm:space-y-0">
          <span>&copy; 2026 ContentForge AI Inc. All rights reserved.</span>
          <div className="flex space-x-6">
            <span className="hover:text-slate-400 transition-colors">Privacy Policy</span>
            <span className="hover:text-slate-400 transition-colors">Terms of Service</span>
            <span className="hover:text-slate-400 transition-colors">Cookie settings</span>
          </div>
        </div>
      </footer>

    </div>
  );
}
